In [67]:
import numpy as np

## Axis
numpy 的核心是 `nadrray`

维度叫做 `axis`。

例如，下面这个具有两个 `axis`，第一个 `axis`（外层）的长度是 2，第二个 `axis`（内层）的长度是 3：

```python
[[1., 0., 0.],
 [0., 1., 2.]]
```

## 创建 ndarray

#### 通过 `python` 的数组来创建

In [68]:
# 创建一个 1D array
a = np.array([2, 3, 4])
print("1d array: \n", a)

# 创建一个 2D array
b = np.array([[1, 2, 3], [4, 5, 6]])
print("2d array: \n", b)

# 指定每个元素的类型，这里是复数
c = np.array([[1, 2], [3, 4]], dtype=complex)
print("complex 2d array: \n", c)

1d array: 
 [2 3 4]
2d array: 
 [[1 2 3]
 [4 5 6]]
complex 2d array: 
 [[1.+0.j 2.+0.j]
 [3.+0.j 4.+0.j]]


#### 通过内置的方法来创建

In [69]:
# 创建全是 0 元素的 ndarry
d = np.zeros((2, 6))
print("zeros: \n", d)

# 创建全是 1 元素的 ndarray
e = np.ones((2, 5), dtype=np.float32)
print("ones: \n", e)

# 指定大小，元素的值都是随机的
f = np.empty((2, 4))
print("empty: \n", f)

zeros: 
 [[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]
ones: 
 [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
empty: 
 [[1. 0. 2. 0.]
 [3. 0. 4. 0.]]


#### 通过 `arange` 和 `linspace` 来创建 `1D` 的 array

In [70]:
# arange 可以指定步长，含头不含尾
a = np.arange(10, 30, 5)
print("arange: \n", a)

# linspace 指定总的元素数量
b = np.linspace(10, 30, 6)
print("linspace: \n", b)

# 配合 reshape 可以得到多维的 array
c = np.arange(12).reshape(2, 2, 3)
print("reshape: \n", c)

arange: 
 [10 15 20 25]
linspace: 
 [10. 14. 18. 22. 26. 30.]
reshape: 
 [[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]]


## ndarray 的一些属性

In [71]:
a = np.array([[2, 4, 5],
             [1, 2, 3]])
print(a)

# ndim 表示维度，或者 axis 的数量
print("ndim: ", a.ndim)

# shape 每个维度的长度
print("shape: ", a.shape)

# size 总的元素数量
print("size: ", a.size)

# dtype 每个元素的类型
print("dtype: ", a.dtype)

# itemsize 每个元素的大小，单位是 byte
print("itemsize: ", a.itemsize)

[[2 4 5]
 [1 2 3]]
ndim:  2
shape:  (2, 3)
size:  6
dtype:  int64
itemsize:  8


## 基本的运算

#### `ndarray` 的运算是对每个元素都生效的，比如：

In [72]:
a = np.arange(4).reshape(2, 2)
print("a: \n", a)
print("a ** 2: \n", a ** 2)
print("np.sin(a): \n", np.sin(a))

a: 
 [[0 1]
 [2 3]]
a ** 2: 
 [[0 1]
 [4 9]]
np.sin(a): 
 [[0.         0.84147098]
 [0.90929743 0.14112001]]


#### 矩阵相关的运算

In [73]:
A = np.array([[1, 1],
              [0, 1]])
B = np.array([[2, 0],
              [3, 4]])
print("A: \n", A)
print("B: \n", B)
# * 表示矩阵逐元素乘积
print("A * B: \n", A * B)

# @ 表示矩阵乘法
print("A @ B: \n", A @ B)

# dot 也表示矩阵乘法
print("A.dot(B): \n", A.dot(B))

A: 
 [[1 1]
 [0 1]]
B: 
 [[2 0]
 [3 4]]
A * B: 
 [[2 0]
 [0 4]]
A @ B: 
 [[5 4]
 [3 4]]
A.dot(B): 
 [[5 4]
 [3 4]]


#### 其他的一些操作

In [74]:
A = np.array([[1, 2, 5],
              [3, 4, 7]])
print("A: \n", A)

# 所有元素的和
print("sum: ", A.sum())

# 所有元素中的最大值
print("max: ", A.max())

# 按列求和，也就是保留第一个 axis
print("sum(axis=0): \n", A.sum(axis=0))

# 按行求和，也就是保留第二个 axis
print("sum(axis=1): \n", A.sum(axis=1))

A: 
 [[1 2 5]
 [3 4 7]]
sum:  22
max:  7
sum(axis=0): 
 [ 4  6 12]
sum(axis=1): 
 [ 8 14]


## 访问矩阵元素

In [75]:
A = np.array([[1, 2, 5],
              [3, 4, 7]])
print("A: \n", A)
# 第一种方法
print("A[1, 2]: ", A[1, 2])

# 第二种方法
print("A[1][2]: ", A[1][2])

A: 
 [[1 2 5]
 [3 4 7]]
A[1, 2]:  7
A[1][2]:  7


#### 按最外层遍历

In [76]:
A = np.array([[1, 2, 5],
              [3, 4, 7]])
print("A: \n", A)
print("rows")
for row in A:
    print(row)

A: 
 [[1 2 5]
 [3 4 7]]
rows
[1 2 5]
[3 4 7]


#### 按元素遍历

In [77]:
A = np.array([[1, 2, 5],
              [3, 4, 7]])
print("A: \n", A)
print("elements")
for e in A.flat:
    print(e)

A: 
 [[1 2 5]
 [3 4 7]]
elements
1
2
5
3
4
7


## 其他

#### 拷贝

In [78]:
# `=` 并不是拷贝
A = np.array([1, 2, 3])
B = A
print("id of A: ", id(A))
print("id of B(=): ", id(B))

# 使用 copy 方法进行拷贝
C = A.copy 
print("id of C(copy): ", id(C))

id of A:  4429073744
id of B(=):  4429073744
id of C(copy):  4429678448


#### 还有其他的功能

- 矩阵拼接
- 矩阵分块
- 通过 view 方法在同一个原始数据上创建出不同的外观

## 为每个元素应用自定义函数

通过 vectorize() 函数实现

注：一定要指定输出元素的类型！！！！！！！！！！！

In [1]:
import numpy as np

def foo(x):
    # odd
    if x % 2 != 1:
        return "odd-{}".format(x)
    else:
        return "even-{}".format(x)

vfoo = np.vectorize(foo, otypes=[str])

A = np.arange(12).reshape(3, 4)
print("A: \n", A)

print("foo(A): \n", vfoo(A))

A: 
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
foo(A): 
 [['odd-0' 'even-1' 'odd-2' 'even-3']
 ['odd-4' 'even-5' 'odd-6' 'even-7']
 ['odd-8' 'even-9' 'odd-10' 'even-11']]
